var Localization_btaudioAppDict_en_UK = {
	//"stringId" : "localString"
	"BTAudio": "Bluetooth - {deviceName}",
	"BTDeviceDisconnect": "BT Device Disconnected",
	"BrowsingUnsupported": "Unable to browse the connected device.",
	"DeviceUnsupported": "Device Not Supported",
	"DeviceUnsupportedDescription": "Would you like to pair another device?",
	"Disconnect": "Bluetooth Connection Lost",
	"MobileDeviceError": "Mobile Device Error",
	"MobileDeviceErrorDescription": "Check your mobile device to make sure everything is functioning properly.",
	"SongUnsupported": "Device Cannot Read File",
	"TooltipRootMenu": "Root Menu",
	"Tooltip_IcnUmpPlayOrStop": "Play/Stop",
	"Unknown": "Unknown",
	"VrHelp_NowPlayingA2DP_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingA2DP_Help_Left2": "Play / Stop",
	"VrHelp_NowPlayingA2DP_Help_Left3": "Sound Settings",
	"VrHelp_NowPlayingA2DP_Help_Left4": "",
	"VrHelp_NowPlayingAVRCP10_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP10_Help_Left2": "Previous",
	"VrHelp_NowPlayingAVRCP10_Help_Left3": "Rewind",
	"VrHelp_NowPlayingAVRCP10_Help_Left4": "Play / Pause",
	"VrHelp_NowPlayingAVRCP10_Help_Left5": "Fast Forward",
	"VrHelp_NowPlayingAVRCP10_Help_Right1": "Next",
	"VrHelp_NowPlayingAVRCP10_Help_Right2": "Sound Settings",
	"VrHelp_NowPlayingAVRCP13_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP13_Help_Left2": "Repeat",
	"VrHelp_NowPlayingAVRCP13_Help_Left3": "Shuffle",
	"VrHelp_NowPlayingAVRCP13_Help_Left4": "Scan",
	"VrHelp_NowPlayingAVRCP13_Help_Left5": "Previous",
	"VrHelp_NowPlayingAVRCP13_Help_Right1": "Rewind",
	"VrHelp_NowPlayingAVRCP13_Help_Right2": "Play / Pause",
	"VrHelp_NowPlayingAVRCP13_Help_Right3": "Fast Forward",
	"VrHelp_NowPlayingAVRCP13_Help_Right4": "Next",
	"VrHelp_NowPlayingAVRCP13_Help_Right5": "Sound Settings",
	"VrHelp_NowPlayingAVRCP14_Help_Left1": "Entertainment",
	"VrHelp_NowPlayingAVRCP14_Help_Left2": "Root Menu",
	"VrHelp_NowPlayingAVRCP14_Help_Left3": "Repeat",
	"VrHelp_NowPlayingAVRCP14_Help_Left4": "Shuffle",
	"VrHelp_NowPlayingAVRCP14_Help_Left5": "Scan",
	"VrHelp_NowPlayingAVRCP14_Help_Right1": "Previous / Next",
	"VrHelp_NowPlayingAVRCP14_Help_Right2": "Rewind",
	"VrHelp_NowPlayingAVRCP14_Help_Right3": "Play / Pause",
	"VrHelp_NowPlayingAVRCP14_Help_Right4": "Fast Forward",
	"VrHelp_NowPlayingAVRCP14_Help_Right5": "Sound Settings",
};

framework.registerAppDictLoaded("btaudio", "en_UK");