var Localization_usbaudioAppDict_en_US = {
	//"stringId" : "localString"
	"Album": "Album",
	"AlbumDisambiguation": "Album Disambiguation",
	"Albums": "Albums",
	"AllAlbums": "All Albums",
	"AllArtists": "All Artists",
	"AllChapters": "All Chapters",
	"AllEpisodes": "All Episodes",
	"AllSongs": "All Songs",
	"Artist": "Artist",
	"Artists": "Artists",
	"Audiobook": "Audiobook",
	"Audiobooks": "Audiobooks",
	"AuthenticationFailure": "Authentication Failure",
	"AuthenticationFailureSBN": "Authentication Failed",
	"Folder": "Folder",
	"Folders": "Folders",
	"Genre": "Genre",
	"Genres": "Genres",
	"IncompatibleFirmware": "Firmware Incompatible",
	"IncompatibleFirmwareSBN": "Firmware Incompatible",
	"NoPlayableFiles": "No Playable Files",
	"NotSupported": "Device Not Supported",
	"NotSupportedSBN": "Device Not Supported",
	"Playlist": "Playlist",
	"Playlists": "Playlists",
	"Podcast": "Podcast",
	"Podcasts": "Podcasts",
	"RootMenu": "Root Menu",
	"Song": "Song",
	"Songs": "Songs",
	"Tooltip_IcnUmpCurrentList": "Song List",
	"USB1Connected": "USB1: {usbName} Connected",
	"USB1Disconnected": "USB1: {usbName} Disconnected",
	"USB2Connected": "USB2: {usbName} Connected",
	"USB2Disconnected": "USB2: {usbName} Disconnected",
	"USBDisconnected": "USB Device Disconnected",
	"USBDisconnectedSBN": "USB Disconnected",
	"UnknownType": "USB Type Unknown",
	"VrHelp_NowPlaying_Help_Left1": "Entertainment",
	"VrHelp_NowPlaying_Help_Left2": "Root Menu",
	"VrHelp_NowPlaying_Help_Left3": "Song List",
	"VrHelp_NowPlaying_Help_Left4": "Repeat",
	"VrHelp_NowPlaying_Help_Left5": "Repeat All",
	"VrHelp_NowPlaying_Help_Right1": "Shuffle",
	"VrHelp_NowPlaying_Help_Right2": "More Like This",
	"VrHelp_NowPlaying_Help_Right3": "Previous / Next",
	"VrHelp_NowPlaying_Help_Right4": "Play / Pause",
	"VrHelp_NowPlaying_Help_Right5": "Sound Settings",
	"VrHelp_USBAudio_Help_Left1": "Playlist",
	"VrHelp_USBAudio_Help_Left2": "Artist",
	"VrHelp_USBAudio_Help_Left3": "Album",
	"VrHelp_USBAudio_Help_Left4": "Song",
	"VrHelp_USBAudio_Help_Left5": "Genre",
	"VrHelp_USBAudio_Help_Right1": "Folders",
	"VrHelp_USBAudio_Help_Right2": "Play All",
	"moreLikeThis": "More Like This",
	"usbaudio": "USB - {deviceName}",
};

framework.registerAppDictLoaded("usbaudio", "en_US");